export const consts = {
  GET_INIT_MOVIES: 'ET_INIT_MOVIES',
  INCREMENT_COUNTER: 'INCREMENT_COUNTER',
  DECREMENT_CONUTER: 'DECREMENT_CONUTER',
  LOGIN_USER: 'LOGIN_USER',
  GET_INPUT: 'GET_INPUT',
  GET_ID: 'GET_ID',
  GET_DETAIL: 'GET_DETAIL',
  SEARCH_MOVIES: 'SEARCH_MOVIES'
}
